### PR TITLE
[WIP] Add binder deps

### PR DESCRIPTION
**Pull request by luizirber**
Hi! I saw you have a `notebooks/` dir, so why not make them executable on mybinder.org? =]

I'm openning the PR early and keeping track of progress in the checklist below.

Temporary link for checking this PR: https://mybinder.org/v2/gh/luizirber/kipoi/binder

### Working

- [x] contributing_models.ipynb [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fcontributing_models.ipynb)
- [x] variant_effect_prediction_simple.ipynb [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fvariant_effect_prediction_simple.ipynb)

### Sort of working

- [ ] mutation_map.ipynb [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fmutation_map.ipynb)
    * takes forever to run (at the `mmp = mm.query_vcf(query_vcf, scores = ["logit"])` step). It eventually finished after 2 hours, but then I got disconnected from Binder while trying to replicate the same work in the CLI section.
- [ ] R-api.ipynb [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2FR-api.ipynb)
  * R kernel and reticulate installed, but not all commands work yet

### Errors

- [ ] composing_models.ipynb [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fcomposing_models.ipynb)
  * ```python-traceback
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-10-0ed80e3c6656> in <module>()
          7             yield (batch['inputs'], batch['targets'])
          8 
    ----> 9 train_gen = create_train_gen(...)
         10 m4.fit_generator(train_gen, ...)
    
    TypeError: create_train_gen() takes 0 positional arguments but 1 was given
    ```
- [ ] gradient_prediction.ipynb [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fgradient_prediction.ipynb)
  * ```python-traceback
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-11-9a1f98751042> in <module>()
          1 # generate the GradPlotter instance:
    ----> 2 gp = GradPlotter(grad_preds, model_name)
    
    <ipython-input-10-af26f475d5b3> in __init__(self, data, model, source, grad_preds)
         60         md = source.get_model_descr(model)
         61 
    ---> 62         if ":" in md.default_dataloader:
         63             dl_source, dl_path = md.default_dataloader.split(":")
         64         else:
    
    TypeError: argument of type 'DataLoaderImport' is not iterable
    ```
- [ ] python-api.ipynb  [Binder](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fpython-api.ipynb)
  * ```python
    >>> MODEL = "rbp_eclip/UPF1"
    >>> model = kipoi.get_model(MODEL)
    Downloading https://sandbox.zenodo.org/record/248594/files/UPF1.dataloader.pkl?download=1 to /home/jovyan/.kipoi/models/rbp_eclip/downloaded/dataloader_files/UPF1/0d302edc6fa91ef8d74dc1c32e0ae9e6
    HTTPError: HTTP Error 404: NOT FOUND
    ```
- [ ] tf_binding_models.ipynb  [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Ftf_binding_models.ipynb)
  * ValueError: model DeepBind/D00776.005 doesn't exist
- [ ] variant_effect_prediction.ipynb  [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/luizirber/kipoi/binder?filepath=notebooks%2Fvariant_effects_prediction.ipynb)
  * `ValueError: dataloader DeepSEA/variantEffects doesn't exist`

### CODE REVIEW

**Comment by Avsecz** [comment]
Absolutely! Great idea! Let me know when you want me to merge the PR

**Comment by luizirber** [comment]
@avsecz not sure how to deal with the errors, seems like they come from outdated notebooks (compare to current APIs/models?)

**Comment by Avsecz** [comment]
Are the notebooks failing? Which one?

**Comment by Avsecz** [comment]
Ups. Haven't seen the error message above. Thanks for posting. I will have a look at it.

**Comment by luizirber** [comment]
I added binder badges to start each notebook. I can try to dig in and fix the errors in the notebook, but I guess you will be able to find the solutions way faster than me =]

**Comment by Avsecz** [comment]
Awesome! I'll fix the notebook. Should be easy

**Comment by Avsecz** [comment]
Sorry for the delay. I'm currently working on integrating the Singularity container https://github.com/kipoi/kipoi/blob/master/envs/Singularity

**Comment by Avsecz** [comment]
I added you as a collaborator to the repo. You can now create new branches directly on the repo

## Update
- [x] composing_models.ipynb -the notebook only highlights the functionality but is not intended to successfully run
- [ ] gradient_prediction.ipynb @krrome can you check that one?
- [ ] python-api.ipynb - we somehow forgot to upload one file. Working on it
- [x] tf_binding_models.ipynb - fixed
- [x] variant_effect_prediction.ipynb fixed

**Pull request closed without merging**
