### PR TITLE
Variant effects fixes

### PR DESCRIPTION
**Pull request by krrome**
Fixes and implements:
#252
#256
#263
Plus an update of the variant effect prediction docs.

Tests have failed due to a different reason:
`test_single_model`  fails with `HAL`, reporting:
```
SafetyError: The package for mkl located at /opt/conda/pkgs/mkl-2018.0.2-1
appears to be corrupted. The path 'lib/libmkl_avx512.so'
has a sha256 mismatch.
  reported sha256: d5ba5e70266a1bd58fd92736ca2def58796c6c423c7a910155c2832f5713f2e1
  actual sha256: 728e2bbec14fef93694f0a40b9966aa01af15983875a8748d3a0cb4651b8b159
```

I don't think that is because of my commit - I hope I didn't mess anything up... If I did please let me know...

### CODE REVIEW

**Comment by Avsecz** [comment]
Looks great in general. Can you make the the CLI interface consistent with the `score_variants` function here: https://github.com/kipoi/kipoi/blob/4bcc0ec0a4f52ba44e310dec70ed0625b4937ae7/kipoi/cli/postproc.py#L185-L214

e.g. I'd rename:
- scoring -> scores
- --vcf_path -> --input_vcf, -i
- --out_vcf_fpath -> --output_vcf, -o
- --output -> -e, --extra_output
- remove --install_req
- scoring_kwargs -> score_kwargs

**Comment by krrome** [comment]
I have renamed the CLI commands and commented in the code. Additionally this PR now also implements / fixes:
#262 
#264 
#266

**Comment by krrome** [comment]
@Avsecz can you please take a look at the circle.ci error, seems to be related to the docker image or something like that...

> Tests have failed due to a different reason:
test_single_model fails with HAL, reporting:

```
SafetyError: The package for mkl located at /opt/conda/pkgs/mkl-2018.0.2-1
appears to be corrupted. The path 'lib/libmkl_avx512.so'
has a sha256 mismatch.
  reported sha256: d5ba5e70266a1bd58fd92736ca2def58796c6c423c7a910155c2832f5713f2e1
  actual sha256: 728e2bbec14fef93694f0a40b9966aa01af15983875a8748d3a0cb4651b8b159
```

**Comment by Avsecz** [comment]
Ok

**Pull request merged**
