### PR TITLE
Update kipoi-utils

### PR DESCRIPTION
**Pull request by Avsecz**

### CODE REVIEW

**Comment by Avsecz** [comment]
I added that already in another PR which I plan to merge soon (https://github.com/kipoi/kipoi/pull/466/files). Seems that an incorrect version of kipoi-utils is getting installed. investigating this now

**Comment by Hoeze** [comment]
ah, just added that in https://github.com/kipoi/kipoi/pull/462
Need that for the CI to work again.

**Comment by Avsecz** [comment]
ok. I will wait until that is merged

**Comment by Hoeze** [comment]
done. CI with auto-deployment is working now

**Comment by Avsecz** [comment]
Awesome!

**Pull request closed without merging**
