### PR TITLE
Pyyaml replace yaml.load()

### PR DESCRIPTION
**Pull request by KalinNonchev**

### CODE REVIEW

**Comment by Avsecz** [comment]
Thanks! Can you please try to fix the build? It seems that the circleci api has changed.

**Comment by KalinNonchev** [comment]
@Avsecz in the new version keys with same names are not supported: https://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
I changed slightly the names of the 2 duplicated keys.

**Comment by Avsecz** [comment]
Please don't do stylistic changes (indenting etc) and code changes in the same PR. It makes it impossible to see what code was actually semantically changed in the PR. Can you please split this PR into two: one just applying the changes related to yaml and the second one doing any lint fixes. Note that I haven't implied any specific restriction on the line length. It may be worth disabling linting in your editor.

**Comment by KalinNonchev** [comment]
sorry, I didn't mean to make any stylistic changes. I reverted it to your version. now you can clearly see what I changed.

**Comment by KalinNonchev** [comment]
I ran the tests locally and they are successful. They fail probably due to pandas version here

**Comment by Avsecz** [comment]
Can you try to fix the pandas issue?

**Comment by KalinNonchev** [comment]
I found that concise uses [deprecated method](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.from_items.html) from pandas, so I rewrite it : https://github.com/gagneurlab/concise/pull/13

**Comment by Avsecz** [comment]
Ok. I've made a new release

**Comment by KalinNonchev** [comment]
Good!

**Comment by Avsecz** [comment]
@Hoeze Is there an automated release to pypi?

**Comment by Hoeze** [comment]
@Avsecz Yes, I did not disable it.
=> If you tag the commit + tests pass, it should be automatically be pushed to PyPI.

**Comment by Avsecz** [comment]
Awesome. I'll push a tagged commit. :+1:

**Pull request merged**
