### PR TITLE
dependabot

### PR DESCRIPTION
**Pull request by KalinNonchev**

### CODE REVIEW

**Comment by KalinNonchev** [comment]
@Avsecz Hi, I integrated dependabot for kipoi and kipoiseq. Dependabot requires [requirements.txt](https://github.com/KalinNonchev/kipoi/blob/master/requirements.txt) to check the dependencies. I used `pipreqs` to create requirements.txt.

**Comment by Avsecz** [comment]
Note that you can also push directly to kipoi/kipoi's repository branches (no need to use the forked repo).

**Comment by KalinNonchev** [comment]
Thanks! I know, but I had to make all these changes on the master branch to test dependabot. Now someone's account should be linked to dependabot to monitor kipoi and kipoiseq on the master branch. Should I use mine?

**Comment by KalinNonchev** [comment]
I can't get permission to link @kipoi to dependabot

**Comment by Avsecz** [comment]
@Hoeze can you use kipoi.bot to setup the dependabot?

**Comment by Hoeze** [comment]
let me check

**Pull request merged**
