### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### kipoi/kipoi now has a Chat Room on Gitter

@xnancy has just created a chat room. You can visit it here: [https://gitter.im/kipoi/kipoi-contribute](https://gitter.im/kipoi/kipoi-contribute?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/kipoi/kipoi-contribute?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Avsecz** [comment]
@xnancy I think we should have only one gitter badge in our readme. Should it be this one or the one we have in the readme currently?

**Comment by xnancy** [comment]
Either, I think kipoi-contribute (this badge) for the github repo and kipoi-feedback for general linking to feedback

**Comment by Avsecz** [comment]
Could we rename one of them to `kipoi-general` and then include it on the main page?

**Comment by Avsecz** [comment]
I'll edit the badge link directly in the readme

**Pull request closed without merging**
